<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0;net9.0;net8.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Valhalla.TestHost</RootNamespace>
    <PackageId>PhoenixToolkits.TestHost</PackageId>
    <Version>0.1.0</Version>
    <Authors>Phoenix</Authors>
    <Company>Valhalla</Company>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageProjectUrl>https://github.com/yggdrasill-dev/PhoenixToolkits.TestHost</PackageProjectUrl>
    <RepositoryUrl>https://github.com/yggdrasill-dev/PhoenixToolkits.TestHost.git</RepositoryUrl>
    <RepositoryType></RepositoryType>
    <PackageTags>test;hosting;integration-testing;generic-host</PackageTags>
    <Description>建立測試用 Generic Host，支援非 Web 專案的整合測試</Description>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net8.0'">
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.*" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net9.0'">
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.*" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net10.0'">
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.*" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="PhoenixToolkits.CodeAnalysis.Analyzers" Version="0.0.14">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
